### ISSUE TITLE
sarif_file cannot be found

### ISSUE THREAD

**Issue by nalum** [kitabisa/gokart-action#3]
I've tried getting this setup with all the default values but I'm getting this error when the job runs:

```
Run github/codeql-action/upload-sarif@v1
  with:
    sarif_file: ../results
    checkout_path: /home/runner/work/dexo-map/dexo-map
    token: ***
    matrix: null
Error: Path does not exist: ../results
Error: Path does not exist: ../results
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:144:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:132:30)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:49:46)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:61:9)
```

Any thoughts on it?

**Comment by miselico** [comment]
I am encountering the same issue. @Nalum did you find a solution?

**Comment by miselico** [comment]
Found a solution now. This can be fixed by adding the arguments explicitly in the config, see #4

**Comment by nalum** [comment]
@miselico thanks for the update, I hadn't gone any further with it. I'll try out the fix you have here when I get the chance :+1:
